# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = gnome-keyring-daemon --start --components=secrets,pkcs11,gpg,ssh

# Apps fijas por workspace
exec-once = [workspace 1 silent] kitty
exec-once = sleep 2 && hyprctl dispatch exec "[workspace 6 silent] kitty"
exec-once = sleep 4 && hyprctl dispatch exec "[workspace 7 silent] google-chrome --profile-directory='Profile 1' --new-window https://supabase.com https://vercel.com https://github.com"
exec-once = sleep 7 && hyprctl dispatch exec "[workspace 8 silent] google-chrome --profile-directory='Default' --new-window https://web.whatsapp.com"
